# Generated by Django 4.2.3 on 2024-01-03 00:16

from django.db import migrations, models
import news.verifications


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(
                max_length=200, validators=[news.verifications.title_verify]
            ),
        ),
    ]
